"use client";

import { createPortal } from "react-dom";
import { useState } from "react";
import { Terminal, Cpu, Fingerprint, AlertCircle, Sparkles } from "lucide-react";

interface WelcomeModalProps {
  isOpen: boolean;
  onClose: () => void;
}

/**
 * 欢迎弹窗组件
 * 
 * 在用户登录后显示产品说明
 * 支持"不再显示"选项，状态存储在 localStorage
 */
export function WelcomeModal({ isOpen, onClose }: WelcomeModalProps) {
  const [dontShowAgain, setDontShowAgain] = useState(false);

  if (!isOpen) return null;
  if (typeof document === "undefined") return null;

  const handleClose = () => {
    if (dontShowAgain) {
      localStorage.setItem("apex_welcome_dismissed", "true");
    }
    onClose();
  };

  return createPortal(
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
      {/* 背景遮罩 */}
      <div 
        className="absolute inset-0 bg-black/80 backdrop-blur-sm" 
        onClick={handleClose}
      />

      {/* 主体弹窗 */}
      <div className="relative z-10 w-full max-w-lg">
        <div className="relative overflow-hidden rounded-2xl border border-purple-500/50 bg-[#0a0a0a]/95 shadow-[0_0_50px_rgba(168,85,247,0.3)] backdrop-blur-xl">
          
          {/* 顶部装饰条 */}
          <div className="h-1 w-full bg-gradient-to-r from-purple-500 via-cyan-500 to-purple-500" />
          
          {/* 扫描线动画 */}
          <div className="pointer-events-none absolute inset-0 opacity-30">
            <div className="scan-line absolute inset-0 bg-gradient-to-b from-transparent via-cyan-500/10 to-transparent" />
          </div>

          {/* 内容区域 */}
          <div className="relative z-10 p-8">
            
            {/* Header */}
            <div className="mb-6 flex items-start gap-4">
              <div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-full border border-cyan-500/30 bg-cyan-950/50">
                <Terminal size={24} className="text-cyan-400" />
              </div>
              <div>
                <h2 className="flex items-center gap-2 text-2xl font-bold tracking-tight text-white">
                  连接已建立 
                  <span className="h-2 w-2 animate-pulse rounded-full bg-green-500" />
                </h2>
                <p className="font-mono mt-1 text-xs tracking-widest text-cyan-500/70">
                  SYSTEM MESSAGE // FROM FOUNDER
                </p>
              </div>
            </div>

            {/* Body Text */}
            <div className="space-y-4 text-sm leading-relaxed text-gray-300">
              <p>
                <strong className="text-white">你好，我是 Apex 小墨。</strong>
              </p>
              
              <p>
                此刻呈现在你眼前的，不仅仅是一个网站，而是一场
                <span className="mx-1 font-bold text-cyan-400 drop-shadow-[0_0_10px_rgba(6,182,212,0.3)]">
                  &ldquo;人机协作&rdquo;
                </span>
                的实验。
              </p>

              <div className="my-4 border-l-2 border-white/10 pl-4 italic text-gray-400">
                &ldquo;代码由 AI 编写，界面由 AI 渲染。而我，是那个创造想法和定义方向的领航员。&rdquo;
              </div>

              <p>
                这证明了在AI时代，<strong className="text-white">个体也能拥有一支数字化军队</strong>。
              </p>

              <div className="flex gap-2 items-start rounded-lg border border-yellow-500/10 bg-yellow-500/5 p-3 text-xs text-yellow-100/80">
                <AlertCircle size={14} className="mt-0.5 shrink-0 text-yellow-500" />
                <span>
                  当前系统处于 <strong className="text-yellow-400">内测阶段</strong>。
                  Apex谈不上是一个产品，也可能存在Bug，我只是想做一个有点酷的主页，并且共享我做的智能体给大家使用，仅此而已，感谢你的每一次反馈，它会继续完善。
                </span>
              </div>
            </div>

            {/* Footer / Action */}
            <div className="mt-8 space-y-4 border-t border-white/10 pt-6">
              
              {/* 不再显示选项 */}
              <label className="flex cursor-pointer items-center gap-2 text-sm text-gray-400 transition-colors hover:text-gray-300">
                <input
                  type="checkbox"
                  checked={dontShowAgain}
                  onChange={(e) => setDontShowAgain(e.target.checked)}
                  className="h-4 w-4 cursor-pointer rounded border-white/20 bg-white/5 text-purple-500 focus:ring-2 focus:ring-purple-500/50 focus:ring-offset-0"
                />
                <span>不再显示此消息</span>
              </label>

              {/* 按钮和标识 */}
              <div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between">
                <div className="font-mono flex items-center gap-2 text-[10px] text-gray-500">
                  <Cpu size={12} />
                  <span>GENERATED BY AI • CURATED BY HUMAN</span>
                </div>

                <button
                  onClick={handleClose}
                  className="group relative flex w-full items-center justify-center gap-2 overflow-hidden rounded-lg bg-gradient-to-r from-purple-500 to-pink-500 px-6 py-2.5 font-bold text-white shadow-[0_0_20px_rgba(168,85,247,0.3)] transition-all hover:from-purple-600 hover:to-pink-600 md:w-auto"
                >
                  <Fingerprint size={18} className="transition-transform group-hover:scale-110" />
                  <span>我已了解，接入系统</span>
                  
                  {/* 按钮光效 */}
                  <div className="absolute top-0 -left-[100%] h-full w-[50%] skew-x-[-20deg] bg-gradient-to-r from-transparent via-white/20 to-transparent transition-all duration-700 group-hover:left-[200%]" />
                </button>
              </div>
            </div>

          </div>

          {/* 背景装饰 Logo (水印) */}
          <div className="pointer-events-none absolute -bottom-10 -right-10 opacity-5">
            <Sparkles size={200} />
          </div>

        </div>
      </div>

      {/* 扫描线动画样式 */}
      <style jsx>{`
        @keyframes scan-line {
          0% { transform: translateY(-100%); }
          100% { transform: translateY(100%); }
        }
        .scan-line {
          animation: scan-line 3s linear infinite;
        }
      `}</style>
    </div>,
    document.body
  );
}
